"""addition

Revision ID: bd1e28fa5a17
Revises: 111a62fbc6d3
Create Date: 2021-06-13 17:16:42.159867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1e28fa5a17'
down_revision = '111a62fbc6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch_category', sa.String(length=20), nullable=True))
    op.add_column('pitch', sa.Column('upvotes', sa.Integer(), nullable=True))
    op.add_column('pitch', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.drop_column('pitch', 'down_vote')
    op.drop_column('pitch', 'up_vote')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_secure', sa.String(length=255), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'password_secure')
    op.drop_column('users', 'password_hash')
    op.add_column('pitch', sa.Column('up_vote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitch', sa.Column('down_vote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'downvotes')
    op.drop_column('pitch', 'upvotes')
    op.drop_column('pitch', 'pitch_category')
    # ### end Alembic commands ###
